version = 1

test_patterns = ["test/**"]

exclude_patterns = ["dist/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]
  plugins = ["angular"]

[[transformers]]
name = "prettier"
enabled = true
