name: webclient-dev

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Node.js, NPM and Yarn
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install and build Angular
        run: |
          npm install
          npm run build:dev

      - name: Publish to dev-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=$(node -p "require('./package.json').version")
          git config --global user.email "support@ctemplar.com"
          git config --global user.name "CTemplar"
          git checkout -B dev-pages
          git add --recur -f dist
          ls -la dist/assets/theme/
          git commit -am "Release v${version}"
          git filter-branch -f --prune-empty --subdirectory-filter dist
          git push -f origin dev-pages
          git checkout -

      - name: Publish to Iceland server
        run: |
          ${{ secrets.DEPLOY_COMMAND }} webclient-dev
